services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend-js/Dockerfile
    # Documents the internal API Port of the container - does not publish it to the host
    expose:
      - "4566"
    # Enable if needed: Exposes the containers internal Port 4566 to the host system through port 8080
    #ports:
    #  - "8080:4566" # if internal port needs to be mapped to a port on the host system

  frontend:
    container_name: HSLU_WEBLAB_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    # Exposes the containers internal Port 80 (right) to the host system through port 80 (left)
    ports:
      - "80:80" # exposes port 80 to the host system
    #depends_on:
     # - backend
