services:
  mongo:
    image: mongo:8
    container_name: hslu_weblab_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "4566"
    environment:
      PORT: 4566
      MONGO_URI: mongodb://mongo:27017/nest
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:4566/api/users').then(response => process.exit(response.ok ? 0 : 1)).catch(() => process.exit(1))"]
      interval: 5s
      timeout: 3s
      retries: 5


  frontend:
    container_name: HSLU_WEBLAB_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy

  mongo-express:
    image: mongo-express:1
    container_name: hslu_weblab_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-data:
